...
[$class: 'ChoiceParameter', choiceType: 'PT_SINGLE_SELECT', filterLength: 1, filterable: false,
                                        name: 'UI_PROJECT_VERSION', randomName: 'choice-parameter-266216487624196',
                script: [
                    $class: 'ScriptlerScript',
                    scriptlerScriptId: 'ReturnNextVersions.groovy',
                    parameters: [
                        [$class: 'org.biouno.unochoice.model.ScriptlerScriptParameter',
                                name: 'job_name', value: "$JOB_NAME"],
                        [$class: 'org.biouno.unochoice.model.ScriptlerScriptParameter',
                                name: 'branch_name', value: "$BRANCH_NAME"],
                        [$class: 'org.biouno.unochoice.model.ScriptlerScriptParameter',
                                name: 'product_name', value: "$UI_PRODUCT_NAME"]
                    ]
                ]
            ],
...