#!groovy

pipeline {
    agent none

    stages {
        stage ("p") {
            parallel {
                stage ("p1") {
                    agent { label "RH7" }

                    stages {
                        stage ("p1s1") {
                            steps {
                                echo "Hello in p1s1"
                            }
                        }

                        stage ("p1s2") {
                            steps {
                                echo "Hello in p1s2"
                            }
                        }
                    }
                }

                stage ("p2") {
                    agent { label "RH7" }

                    stages {
                        stage ("p2s1") {
                            steps {
                                echo "Hello in p2s1"
                            }
                        }
                    }
                }
            }
        }
    }
}