#!/bin/bash
#
# Commands that show the problem:

if [ ! -f ../jenkins-plugin-manager-2.11.1.jar ]; then
  wget https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.11.1/jenkins-plugin-manager-2.11.1.jar
  mv jenkins-plugin-manager-2.11.1.jar ..
fi
if [ ! -d plugins ]; then
  mkdir plugins
fi
java -jar ../jenkins-plugin-manager-2.11.1.jar --jenkins-version 2.322 --latest false --plugin-download-directory plugins --plugin-file plugins.txt

if [ ! -f ../jenkins-2.322.war ]; then
  wget https://get.jenkins.io/war/2.322/jenkins.war
  mv jenkins.war ../jenkins-2.322.war
fi
JENKINS_HOME=. java -jar ../jenkins-2.322.war
