pipeline {
  agent any
  
  stages {
    stage('Experimenting') {
      steps {
        echo 'Build number: ${env.BUILD_NUMBER}'
        echo 'Build number: $BUILD_NUMBER'
        echo 'Build number: ${ENV.BUILD_NUMBER}'
        echo 'Build number: env.${BUILD_NUMBER}'
        echo 'Build number: env.$BUILD_NUMBER'
        echo 'Build number: "${env.BUILD_NUMBER}"'
        echo 'Build number: env."${BUILD_NUMBER}"'
        echo 'Workspace: ${env.WORKSPACE}'
        echo 'Git branch: ${env.GIT_BRANCH}'
        echo 'Git commit: ${env.GIT_COMMIT}'
      }
    }
  }
}