pipeline{
    agent any
    stages{
        stage('one'){
            stages{
                stage('two'){
                    stages{
                        stage('three'){
                            stages{
                                stage('four'){
                                    steps {
                                        echo 'test'
                                    }
                                }
                            }
                        }
                    }
                }
                stage('five'){
                    steps {
                        echo 'test'
                    }
                }
            }
        }
    }
}
