@Library('myPipelineLib') _

emailBreaks {
    mailingList = 'user@example.com'
    
    node('master') {
        git 'https://git.example.org/user/pipeline-build-failures.git'
        //sh 'true'
        sh 'might fail'
    }
}
